// examples/angular/puqu-printer.component.ts
import { Component, ElementRef, OnDestroy, ViewChild } from '@angular/core'
import { PuquWebBluetoothPrinter, type PrinterSnapshot } from 'puquprintjs'

@Component({
  selector: 'app-puqu-printer',
  standalone: true,
  template: `
    <button [disabled]="state.connecting" (click)="connect()">连接璞趣打印机</button>
    <button [disabled]="!state.connected || state.printing" (click)="print()">打印</button>
    <canvas #label width="400" height="240"></canvas>
    <span>{{ state.error || state.statusText }}</span>
  `,
})
export class PuquPrinterComponent implements OnDestroy {
  @ViewChild('label') label?: ElementRef<HTMLCanvasElement>
  readonly printer = new PuquWebBluetoothPrinter()
  state: PrinterSnapshot = this.printer.getSnapshot()
  private readonly unsubscribe = this.printer.subscribe(snapshot => { this.state = snapshot })

  connect() { return this.printer.connect() }
  print() { return this.label && this.printer.printCanvas(this.label.nativeElement) }
  ngOnDestroy() { this.unsubscribe(); this.printer.disconnect() }
}

// examples/vue/PuquPrinter.vue
<script setup lang="ts">
import { onBeforeUnmount, ref } from 'vue'
import { PuquWebBluetoothPrinter } from 'puquprintjs'

const printer = new PuquWebBluetoothPrinter()
const canvas = ref<HTMLCanvasElement>()
const state = ref(printer.getSnapshot())
const unsubscribe = printer.subscribe(snapshot => { state.value = snapshot })
onBeforeUnmount(() => unsubscribe())
</script>

<template>
  <button :disabled="state.connecting" @click="printer.connect()">连接璞趣打印机</button>
  <button :disabled="!state.connected || state.printing" @click="canvas && printer.printCanvas(canvas)">打印</button>
  <canvas ref="canvas" width="400" height="240" />
  <span>{{ state.error || state.statusText }}</span>
</template>
